# Generated by Django 5.0 on 2023-12-28 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodrecipe',
            name='description',
            field=models.TextField(default='default'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='foodrecipe',
            name='ingredients',
            field=models.TextField(default='default'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='foodrecipe',
            name='method',
            field=models.TextField(default='default'),
            preserve_default=False,
        ),
    ]
